# Generated by Django 3.1.6 on 2022-03-30 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('customer_photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('customer_video', models.FileField(blank=True, upload_to='uploads/')),
                ('status', models.BooleanField(default=False)),
                ('dob', models.DateField(blank=True)),
                ('country', models.CharField(blank=True, max_length=155)),
                ('passport', models.CharField(blank=True, max_length=15)),
                ('nationality', models.CharField(blank=True, max_length=155)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=155)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
