# Generated by Django 3.1.6 on 2022-03-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('customer_photo', models.FileField(upload_to='uploads/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
