# Generated by Django 3.1.6 on 2022-03-24 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=155)),
                ('admin_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
