# Generated by Django 3.1.6 on 2022-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20220330_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_video',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
